### ISSUE TITLE
测试用例的编号未按规律显示

### ISSUE THREAD

**Issue by liuqingqing01** [aaronchen2k/ngtesting-platform#22]
1.打开多个（例如5个）空的测试用例输入框，在5个用例框中输入字符，从下到上点击每条用例后的保存按钮，保存完后，点击跳转到其他页面，再返回到此页面，页面中的用例编号未按规律显示
2.打开多个（例如5个）空的测试用例输入框，在5个用例框中输入字符，从下到上点击每条用例后的保存按钮，保存完后，点击左上角的保存按钮，点击跳转到其他页面，再返回到此页面，页面中的用例编号未按规律显示

**Comment by aaronchen2k** [comment]
Fixed
