### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by mahaixue** [aaronchen2k/ngtesting-platform#28]
统计的改进建议
第一个是统计每个项目的总体情况 ，总case数，case（未执行，执行成功和执行失败
第二呢就是统计每个测试人员的编写CASE总数。（横坐标是人员，纵坐标是case总数）
第三呢是能统计每个测试人员执行CASE总数。（横坐标是人员，纵坐标不同颜色显示case执行成功数，失败数，总数）

以上最好是有时间筛选，最大筛选范围是一年，默认是一周

**Comment by aaronchen2k** [comment]
Got it!
第一步增加 项目组&项目级的、按人员的用例编写数量统计
有关执行的统计，与预计会放在TestPlan上
