### ISSUE TITLE
你好，部署过程中，打开了注册页面，但是注册不了

### ISSUE THREAD

**Issue by LianWilliam** [aaronchen2k/ngtesting-platform#30]
前台页面：
![image](https://user-images.githubusercontent.com/35838730/39688601-1467e3fe-5206-11e8-9bc6-8482b4cecef9.png)

数据库：
![image](https://user-images.githubusercontent.com/35838730/39688543-d8d564ba-5205-11e8-8615-e92e65f61530.png)

mysql> CREATE DATABASE `ngtesting-dump`;

mysql> use ngtesting-dump;

mysql> source /opt/tomcat/apache-tomcat-8.0.51/webapps/platform/ngtesting-platform-master/xdoc/ngtesting-dump.sql

数据库脚本ngtesting-dump.sql已经导入了，

还需要建什么用户密码什么的吗？

**Comment by aaronchen2k** [comment]
请确保编译后WEB-INF/classes/config.properties里的数据库、用户和密码的配置正确
