### ISSUE TITLE
创建测试集时选择的测试用例数显示错误

### ISSUE THREAD

**Issue by timfang0215** [aaronchen2k/ngtesting-platform#31]
创建测试集时选择的测试用例数显示错误，测试用例数目会把目录数也统计进去，详情请阅附件图片：
![image](https://user-images.githubusercontent.com/39322557/40094285-a3be13c2-58f8-11e8-8244-3ea89ba29187.png)
![image](https://user-images.githubusercontent.com/39322557/40094298-b7688182-58f8-11e8-975a-337712571754.png)

**Comment by aaronchen2k** [comment]
Fixed
