### ISSUE TITLE
缺少tst_case数据表

### ISSUE THREAD

**Issue by isisiwish** [aaronchen2k/ngtesting-platform#33]
1. 新建`ngtesting`数据库
2. 导入`ngtesting-dump.sql`数据
3. 修改`config.properties`，datasource.jdbc.url
4. 打包部署至`:8080/test/`路径下
5. 注册信息被js提交到`localhost`
6. 修改`main.86b311621dffb0659e15.bundle.js`，`SERVICE_URL:"http://`为本地URL
7. 继续提交注册信息，后台日志提示`Table 'ngtesting.tst_case' doesn't exist`
8. 数据库，缺少`tst_case`数据表
9. `ngtesting-dump.sql`，没有`tst_case`建表语句

还麻烦指教下。

**Comment by aaronchen2k** [comment]
不用脚本创建，当启动tomcat程序时，会自动创建其他表

**Comment by isisiwish** [comment]
嗯嗯，这个问题已经解决，当时网络有点问题，那张表没有建起来，重新来了次就好了。
