### ISSUE TITLE
二次开发问题

### ISSUE THREAD

**Issue by zlp19860220** [aaronchen2k/ngtesting-platform#34]
您好，想问一下前端webapps下的代码是源码么？
我想在ngtesting上加上测试用例导入的功能，不知道如何入手。
index.html的body里的app节点内容是如何生成的？找不到对应的内容
麻烦回答一下。

**Comment by aaronchen2k** [comment]
前端用的是AngualrJS，运行时会自动构建HTML的整个DOM，目前前端的源代码没有开放
