### ISSUE TITLE
建了个测试计划，并执行，然后删除了改测试计划，但是这个页面 这块数据还在。这里也应该删除比较好

### ISSUE THREAD

**Issue by mysterylx** [aaronchen2k/ngtesting-platform#43]
![image](https://user-images.githubusercontent.com/1650388/44579005-9ed6ae00-a7c7-11e8-919a-ac8eeec11086.png)

**Comment by aaronchen2k** [comment]
Fixed

下一个版本中会更新存储过程 chart_execution_process_by_project

`BEGIN

set @sumNumb:= 0;

IF project_type='project' THEN
    select days.date date, IFNULL(temp.`status`,'null') `status`, IFNULL(temp.numb,0) numb 
	from 
        (select @num:=@num-1, date_format(adddate(CURDATE(), INTERVAL -@num DAY),'%Y/%m/%d') as date
            from SysNums,(select @num:=numb) t 
            where adddate(CURDATE(), INTERVAL -@num DAY) <= date_format(curdate(),'%Y/%m/%d') and @num > 0
            order by date) days 
	left join 
        (
            SELECT COUNT(csr.id) numb, DATE_FORMAT(csr.exeTime,'%Y/%m/%d') dt, csr.`status` `status` 
                FROM TstCaseInTask csr 
		JOIN TstPlan plan on csr.planId = plan.id
		JOIN TstTask task on csr.taskId = task.id

                WHERE csr.projectId=project_id  
                    AND csr.isLeaf=true AND csr.deleted != true AND csr.disabled != TRUE
                    AND csr.`status` != 'untest' 
		    AND plan.deleted != true AND task.deleted != true
		GROUP BY dt, csr.`status`
        ) temp ON days.date = temp.dt
		
     ORDER BY days.date, temp.`status`;

ELSEIF project_type='group' THEN
    select days.date date, IFNULL(temp.`status`,'null') `status`, IFNULL(temp.numb,0) numb from 
        (select @num:=@num-1, date_format(adddate(CURDATE(), INTERVAL -@num DAY),'%Y/%m/%d') as date
            from SysNums,(select @num:=numb) t 
            where adddate(CURDATE(), INTERVAL -@num DAY) <= date_format(curdate(),'%Y/%m/%d') and @num > 0
            order by date) days 
	left join 
        (
            SELECT COUNT(csr.id) numb, DATE_FORMAT(csr.exeTime,'%Y/%m/%d') dt, csr.`status` `status` 
                FROM TstCaseInTask csr 
		JOIN TstPlan plan on csr.planId = plan.id
		JOIN TstTask task on csr.taskId = task.id

                WHERE csr.projectId in (SELECT p.id from TstProject p where p.parentId = project_id 
                                AND p.deleted != true AND p.disabled != true)  
                    AND csr.isLeaf=true AND csr.deleted != true AND csr.disabled != TRUE
                    AND csr.`status` != 'untest' 
		    AND plan.deleted != true AND task.deleted != true
		GROUP BY dt, csr.`status`
        ) temp ON days.date = temp.dt
    
     ORDER BY days.date, temp.`status`;

ELSEIF project_type='org' THEN
    select days.date date, IFNULL(temp.`status`,'null') `status`, IFNULL(temp.numb,0) numb from 
        (select @num:=@num-1, date_format(adddate(CURDATE(), INTERVAL -@num DAY),'%Y/%m/%d') as date
            from SysNums,(select @num:=numb) t 
            where adddate(CURDATE(), INTERVAL -@num DAY) <= date_format(curdate(),'%Y/%m/%d') and @num > 0
            order by date) days 
	left join 
        (
            SELECT COUNT(csr.id) numb, DATE_FORMAT(csr.exeTime,'%Y/%m/%d') dt, csr.`status` `status` 
                FROM TstCaseInTask csr 
		JOIN TstPlan plan on csr.planId = plan.id
		JOIN TstTask task on csr.taskId = task.id

                WHERE csr.projectId in (SELECT p.id from TstProject p where p.orgId = project_id 
                                AND p.deleted != true AND p.disabled != true)  
                    AND csr.isLeaf=true AND csr.deleted != true AND csr.disabled != TRUE
                    AND csr.`status` != 'untest' 
		    AND plan.deleted != true AND task.deleted != TRUE

	    GROUP BY dt, csr.`status`
        ) temp ON days.date = temp.dt
    
    ORDER BY days.date, temp.`status`;

END IF;

END`
