### ISSUE TITLE
按照docker安装步骤，不改变任何代码及配置、参数等情况下，网站数据存到哪个库里去了？

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/ngtesting-platform#44]
在自己的云服务器上，按照所描写的docker安装启动步骤，不改变任何代码及配置、参数等情况下，启动成功。
但是注册成功之后，包括注册成功后在系统中的一系列操作，在云服务的的本地数据库中均找不到一点数据。 
是不是没存到本地数据库？  数据存哪里去了？

**Comment by aaronchen2k** [comment]
安装脚本会在云服务器上生成两个Docker实例，分别运行了MySQL和SpringBoot服务，故用户产生的数据会被写入云服务器上的MySQL Docker实例中。

可以先用telnet <云服务的IP> 3306 来确认云服务的3306端口是可以被远程访问的。
再通过 mysql -h<云服务的IP> -uroot -p 来访问此数据库。

**Comment by bitlin** [comment]
嗯，可以连通docker中的mysql数据库了。多谢~
