### ISSUE TITLE
创建测试集，选择用例时候如果勾选耗时，无法选择测试用例（测试用例被隐藏）

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/ngtesting-platform#48]
![image](https://user-images.githubusercontent.com/14798891/45582231-cdcfd380-b8de-11e8-9727-1a107b2fa2f4.png)

![image](https://user-images.githubusercontent.com/14798891/45582235-dfb17680-b8de-11e8-80e0-79677c2a4189.png)

**Comment by aaronchen2k** [comment]
你选择了“大于一小时”，页面则制定进行过滤，仅显示“大于一小时”的用例了
