### ISSUE TITLE
测试集中，已经选择的用例，进去查看木有显示所选中的用例

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/ngtesting-platform#49]
![image](https://user-images.githubusercontent.com/14798891/45583107-82252600-b8ee-11e8-8219-e13c83e1f199.png)

![image](https://user-images.githubusercontent.com/14798891/45583108-89e4ca80-b8ee-11e8-8248-3aeb744e699a.png)

**Comment by aaronchen2k** [comment]
主版本中，已修复
