### ISSUE TITLE
用例评审能否通过的权限能否单独指派给某人呢?

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/ngtesting-platform#50]
多人测试的团队中，测试工程师在用例设计完成之后，需要由项目测试负责人对测试质量进行评估，并标记评审通过或失败。那么就需要把这个评审修改权限隔离出来

**Comment by aaronchen2k** [comment]
后续版本会加上

**Comment by aaronchen2k** [comment]
在主版本中已修复，默认只有测试主管有用例评审权限
