### ISSUE TITLE
用例评审通过或失败，为什么还要停留在当前页面呢？出于什么考虑？

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/ngtesting-platform#53]
![image](https://user-images.githubusercontent.com/14798891/46916792-f20ff480-cff1-11e8-9aac-5439cbab8208.png)

**Comment by aaronchen2k** [comment]
你是希望跳转到下一个用例？

**Comment by bitlin** [comment]
现在放着这两个按钮“评审通过”和“评审失败”，如果不看操作日志记录，很难去识别出这条用例到底是成功还是失败的。

个人认为，可以做个开关按钮或者下拉选项，既可以进行状态变更的操作又可以标识出当前用例的实际状态是通过还是失败。同时觉得，“保存”按钮最好也换个位置，以免造成误解，放右下角也挺好呢

**Comment by aaronchen2k** [comment]
谢谢你的建议！
目前的设计是，当有多个用例时，评审完会跳转到下一个用例，并且当前用例会被标为三种不同的颜色。

**Comment by aaronchen2k** [comment]
Fixed 谢谢
