### ISSUE TITLE
用例无法删除，接口报错”{msg: "业务处理错误", code: 101}“

### ISSUE THREAD

**Issue by bitlin** [aaronchen2k/ngtesting-platform#56]
添加用例之后，删除用例；刷新页面用例还在，无法删除。
发现接口调用https://139.224.8.129/api/v1/client/case/delete ，返回 {"msg":"业务处理错误","code":101}
![ngtesting 无法删除用例](https://user-images.githubusercontent.com/14798891/54370553-c5502e00-46b2-11e9-8359-100fc3443496.jpg)

**Comment by aaronchen2k** [comment]
Fixed

可通过在现有postgresql数据库中运行以下脚本解决：

`CREATE OR REPLACE FUNCTION public.remove_case_and_its_children(
	p_case_id integer,
	p_project_id integer)
    RETURNS integer
    LANGUAGE 'plpgsql'

    COST 100
    VOLATILE 
AS $BODY$  
declare  
    v_cnt integer;  
BEGIN  
	update "TstCase" set deleted = true where id = any (
		WITH RECURSIVE cs AS ( 
			 SELECT parent.* FROM "TstCase" parent WHERE parent.id = p_case_id
			 union  all 
			 SELECT child.* FROM "TstCase" child, cs WHERE child."pId" = cs.id 
		) 
		SELECT cs.id FROM cs where cs."projectId"=p_project_id ORDER BY cs.id
	);
	
	GET DIAGNOSTICS v_cnt = ROW_COUNT;
	RAISE NOTICE 'v_cnt = %', v_cnt;
	
    RETURN v_cnt;  
END;  
$BODY$;

ALTER FUNCTION public.remove_case_and_its_children(integer, integer)
    OWNER TO ngtesting;
`
