### ISSUE TITLE
新增组织后，编辑组织，更新组织名称时，updatetime 为null 空指针异常，保存失败

### ISSUE THREAD

**Issue by yangjing1127** [aaronchen2k/ngtesting-platform#57]
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2d5b0b03] was not registered for synchronization because synchronization is not active
ngtesting-web_1       | JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@7b8b7976] will not be managed by Spring
ngtesting-web_1       | ==>  Preparing: SELECT * FROM "TstOrg" o WHERE o.id = ? 
ngtesting-web_1       | ==> Parameters: 2(Integer)
ngtesting-web_1       | <==    Columns: id, name, website, disabled, deleted, createTime, updateTime
ngtesting-web_1       | <==        Row: 2, 测试培训, study, f, f, 2019-09-29 03:45:16.429, null
ngtesting-web_1       | <==      Total: 1
ngtesting-web_1       | Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2d5b0b03]
ngtesting-web_1       | 2019-09-29 03:47:35.413  INFO 70 --- [-nio-443-exec-6] c.n.platform.config.AuthAminAspect       : Response: {code=1, data=com.ngtesting.platform.model.TstOrg@5d5a8471}
ngtesting-web_1       | java.lang.NullPointerException
ngtesting-web_1       | 	at com.ngtesting.platform.servlet.AuthAspect.before(AuthAspect.java:125)
ngtesting-web_1       | 	at sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
ngtesting-web_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ngtesting-web_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
ngtesting-web_1       | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
ngtesting-web_1       | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:626)
ngtesting-web_1       | 	at org.springframework.aop.aspectj.AspectJMethodBeforeAdvice.before(AspectJMethodBeforeAdvice.java:44)
ngtesting-web_1       | 	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
ngtesting-web_1       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
ngtesting-web_1       | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
ngtesting-web_1       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
ngtesting-web_1       | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
ngtesting-web_1       | 	at com.ngtesting.platform.action.admin.OrgAdmin$$EnhancerBySpringCGLIB$$cac9178e.update(<generated>)
ngtesting-web_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ngtesting-web_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ngtesting-web_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ngtesting-web_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
ngtesting-web_1       | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
ngtesting-web_1       | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
ngtesting-web_1       | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
ngtesting-web_1       | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
ngtesting-web_1       | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
ngtesting-web_1       | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
ngtesting-web_1       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
ngtesting-web_1       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
ngtesting-web_1       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
ngtesting-web_1       | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
ngtesting-web_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
ngtesting-web_1       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
ngtesting-web_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:60)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
ngtesting-web_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
ngtesting-web_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
ngtesting-web_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
ngtesting-web_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
ngtesting-web_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ngtesting-web_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ngtesting-web_1       | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
ngtesting-web_1       | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
ngtesting-web_1       | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:613)
ngtesting-web_1       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
ngtesting-web_1       | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
ngtesting-web_1       | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
ngtesting-web_1       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
ngtesting-web_1       | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
ngtesting-web_1       | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
ngtesting-web_1       | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
ngtesting-web_1       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
ngtesting-web_1       | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
ngtesting-web_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
ngtesting-web_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
ngtesting-web_1       | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ngtesting-web_1       | 	at java.lang.Thread.run(Thread.java:745)

**Comment by aaronchen2k** [comment]
已修复
