### ISSUE TITLE
修改测试用例顺序时，SQL报错，无法正常修改用例顺序

### ISSUE THREAD

**Issue by yangjing1127** [aaronchen2k/ngtesting-platform#58]
![TIM截图20191021140020](https://user-images.githubusercontent.com/24238959/67180238-93066c00-f40b-11e9-9645-1515d7580c9e.png)

update 语句有问题吧

**Comment by aaronchen2k** [comment]
是release版本，还是最新的代码？

**Comment by yangjing1127** [comment]
2019-10-12 docker pull 下来的

**Comment by aaronchen2k** [comment]
新的postgresql对update语句的表别名有了更严格的要求，已修复。
需要从
`UPDATE [TABLE] AS T SET T.TID=1,T.TNAME='Name',T.TClass=1 WHERE T.ID=10`
修改为
`UPDATE T SET T.TID=1,T.TNAME='Name',T.TClass=1 FROM [TABLE] T WHERE T.ID=10`
