### ISSUE TITLE
查看项目报错

### ISSUE THREAD

**Issue by woaimama** [aaronchen2k/ngtesting-platform#59]
查看项目报错

**Comment by woaimama** [comment]
![微信图片_20191104111520](https://user-images.githubusercontent.com/56717401/68097875-77639100-fef4-11e9-8ec7-11e6a34cdfad.png)
![微信图片_20191104111525](https://user-images.githubusercontent.com/56717401/68097878-7894be00-fef4-11e9-8914-19bd38521afb.png)

**Comment by aaronchen2k** [comment]
Fixed by refresh auth info after creating a new project
