### ISSUE TITLE
左侧导航栏与右侧内容重合

### ISSUE THREAD

**Issue by woshihuangjin** [aaronchen2k/ngtesting-platform#6]
![3 6ngtesting](https://user-images.githubusercontent.com/37101528/37021085-4004ea8a-2159-11e8-81a4-90f436a0e96f.png)

**Comment by aaronchen2k** [comment]
左边设置最小宽度
增加右边背景的Z-INDEX值

**Comment by aaronchen2k** [comment]
已修复
