### ISSUE TITLE
切换不同的项目查看用例，显示的用例名称一样；用例显示异常

### ISSUE THREAD

**Issue by yangjing1127** [aaronchen2k/ngtesting-platform#62]
![微信图片_20191120163143](https://user-images.githubusercontent.com/24238959/69221948-692f9900-0bb3-11ea-8796-4c7ac08f593d.png)
![2](https://user-images.githubusercontent.com/24238959/69221952-6a60c600-0bb3-11ea-910b-8899fe2a1bec.png)

**Comment by aaronchen2k** [comment]
镜像已更新，请更新容器。

**Comment by yangjing1127** [comment]
已修复
