### ISSUE TITLE
项目添加成员，并分配项目角色-流程异常

### ISSUE THREAD

**Issue by yangjing1127** [aaronchen2k/ngtesting-platform#63]
前置条件：已经为项目添加了多个用户，查看项目成员时，不显示其他人员
操作1：在上面模糊查询 并选择角色点击保存
结果1：已添加的用户显示出来
操作2：为这些用户分配角色
结果2：项目成员列表清空，又不显示
参考动态截图
![项目添加成员，并分配角色-流程异常](https://user-images.githubusercontent.com/24238959/69292555-67acb200-0c41-11ea-8402-4fc67e99c78c.gif)

**Comment by aaronchen2k** [comment]
Fixed
