### ISSUE TITLE
操作和期望结果靠的太近

### ISSUE THREAD

**Issue by woshihuangjin** [aaronchen2k/ngtesting-platform#7]
![3 6ngtesting](https://user-images.githubusercontent.com/37101528/37021352-35a4cb40-215a-11e8-8fa0-1e22743aa1b5.png)

**Comment by aaronchen2k** [comment]
内容过长时，换行显示

**Comment by aaronchen2k** [comment]
开发环境已修复

**Comment by aaronchen2k** [comment]
操作和期望结果间增加了间隙
